language: node_js
node_js:
  - "10.0.0"

jobs:
  include:
    - stage: npm release
      node_js: "10.0.0"
      script: npm i && npm install -g typescript
      deploy:
        provider: npm
        email: "support@snax.one"
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          branch: master
